package main

// excludedFolders is a map of folder names that should not be scanned or watched.
var excludedFolders = map[string]struct{}{
	"node_modules": {},
	"vendor":       {},
	".svn":         {},
	".hg":          {},
	".bzr":         {},
	"_vendor":      {},
	"godeps":       {},
	"bin":          {},
	"obj":          {},
	"tmp":          {},
	"build":        {},
	".vscode":      {},
	"dist":         {},
	"__pycache__":  {},
	".cache":       {},
	"coverage":     {},
	"target":       {},
	"out":          {},
	".idea":        {},
	".gradle":      {},
	".terraform":   {},
	"env":          {},
	".ds_store":    {},
	".next":        {},
	".nuxt":        {},
	".expo":        {},
	".circleci":    {},
	".github":      {},
	".gitlab":      {},
	".vagrant":     {},
	".serverless":  {},
}
